name: Build and Deploy

on:
  push:
    branches:
      - main  # Altere para a branch principal do seu projeto

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - 
          export PATH="$HOME/.poetry/bin:$PATH"
          poetry --version

      - name: Install dependencies
        run: |
          poetry install --no-dev

      - name: Build Docker image
        run: |
          docker build -t myapp .

      - name: Run tests
        run: |
          docker run --rm myapp pytest

      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/v1/services/your-service-id/deployments \
          -H "Authorization: Bearer your-api-key"
